[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_3 = "CRY5Vcb5zLCk4ej8eTu7aCHWpvPT7SDSJyVSrMQyWrY2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
